#!/usr/bin/env python
# -*- coding: utf-8 -*-

# For Python 2 only

from ast import *

# Detect Python that is not version 2 and try to use python2
import sys
import subprocess as sp
import inspect
from os import path

if sys.version_info.major != 2:
    python_2_path = str(sp.check_output('which python2', shell=True))
    python_2_path = python_2_path[2:-3]
    this_script = path.abspath(inspect.getfile(inspect.currentframe()))
    try:
        sp.call([python_2_path, this_script])
    except OSError:
        print('Unable to find Python 2. This script requires Python 2 to run')
        sys.exit(1)

    sys.exit(0)


class replaceXchatCalls(NodeTransformer):
    _remove = [
        'hook_command',
        'hook_print',
        'hook_server',
        'hook_timer',
        'hook_unload',
        'unhook',
        'emit_print',
    ]

    _replace_with_print = [
        'command',
        'prnt',
    ]

    # NOTE Not very context sensitive
    _variables = {}

    NORMAL_RETURN_XCHAT_OFFSET = 4

    def visit_Import(self, node):
        """ Remove *import xchat* statement """

        for alias in node.names:
            if alias.name == 'xchat':
                print('Removing "import xchat"')
                return None

        return node

    def visit_Assign(self, node):
        """ Remove xchat.get_*() and xchat.find_context() assignments """

        for tnode in node.targets:
            if isinstance(tnode, Name) and isinstance(node.value, Call):
                attr = getattr(node.value, 'func', None)
                if isinstance(attr, Attribute) and \
                        getattr(attr.value, 'id', None) == 'xchat':
                    if getattr(self._variables, attr.attr, False) is False:
                        self._variables[attr.attr] = []

                    self._variables[attr.attr].append(tnode.id)
                    print('%d Removing assignment "%s = xchat.%s()"') % \
                        (tnode.lineno, tnode.id, attr.attr)
                    return None
        return node

    def visit_Return(self, node):
        """ Remove/replace all xchat.* return statements """

        if isinstance(node.value, Attribute) and \
                node.value.value.id == 'xchat':
            if node.col_offset == self.NORMAL_RETURN_XCHAT_OFFSET:
                print('%d Removing "return xchat.%s"' %
                      (node.value.lineno, node.value.attr))
                return None

            print('%d Replacing "return.%s" with "return"' %
                  (node.value.lineno, node.value.attr))
            return copy_location(Return(value=None), node)
        return node

    def visit_Expr(self, node):
        if isinstance(node.value, Call):
            if hasattr(node.value.func, 'attr') \
                    and node.value.func.attr in self._replace_with_print:
                print('%d Replacing "%s.%s()" call with regular print' %
                      (node.value.func.lineno, node.value.func.value.id,
                       node.value.func.attr))
                return copy_location(Print(
                    dest=None,
                    values=node.value.args,
                    nl=True
                ), node)
            elif hasattr(node.value.func, 'attr') \
                    and node.value.func.attr in self._remove:
                func = node.value.func

                print('%d Removing "xchat.%s()" call') % \
                     (func.lineno, func.attr)
                special_arg = Num(n=0)
                if node.value.args[1].id.startswith('net'):
                    special_arg = List(elts=[
                        Str(s=''),
                        Str(s='eth0')],
                        ctx=Load())

                arguments = [special_arg, Num(n=0), Num(n=0)]

                return copy_location(Expr(value=Call(func=Name(
                    id=node.value.args[1].id,
                    ctx=Load()
                ), args=arguments,
                    keywords=[], starargs=None, kwargs=None)), node)
        return node

with open('./xsys.py') as f:
    top_node = parse(''.join(f))
    ast = replaceXchatCalls().visit(top_node)
    ast = fix_missing_locations(ast)
    print('')
    eval(compile(ast, '<string>', 'exec'))
